// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwkHN2NRIuqhcRcHiajrSZy2LZa4gjTxI',
    appId: '1:746788243478:web:6ed9aadd0c892cc1dd4d37',
    messagingSenderId: '746788243478',
    projectId: 'auth-d2294',
    authDomain: 'auth-d2294.firebaseapp.com',
    storageBucket: 'auth-d2294.firebasestorage.app',
    measurementId: 'G-CK9WR113QN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7ZDfPtk8jdY73P4wwpabns0Ha4j_Ar6E',
    appId: '1:746788243478:android:b243d6f69fc0aa97dd4d37',
    messagingSenderId: '746788243478',
    projectId: 'auth-d2294',
    storageBucket: 'auth-d2294.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuGpLblPz8RMK_pt5AqNc5EG8kqPUNc6E',
    appId: '1:746788243478:ios:aa7bc086ba9419d3dd4d37',
    messagingSenderId: '746788243478',
    projectId: 'auth-d2294',
    storageBucket: 'auth-d2294.firebasestorage.app',
    iosBundleId: 'com.example.googleAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuGpLblPz8RMK_pt5AqNc5EG8kqPUNc6E',
    appId: '1:746788243478:ios:aa7bc086ba9419d3dd4d37',
    messagingSenderId: '746788243478',
    projectId: 'auth-d2294',
    storageBucket: 'auth-d2294.firebasestorage.app',
    iosBundleId: 'com.example.googleAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwkHN2NRIuqhcRcHiajrSZy2LZa4gjTxI',
    appId: '1:746788243478:web:889bd5697ce93739dd4d37',
    messagingSenderId: '746788243478',
    projectId: 'auth-d2294',
    authDomain: 'auth-d2294.firebaseapp.com',
    storageBucket: 'auth-d2294.firebasestorage.app',
    measurementId: 'G-G486F83CTB',
  );
}
